name: Publish

on:
  push:
    branches:
     - 'master'
  workflow_dispatch: 

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-central-1
  VERSION: ${{ env.GITHUB_RUN_ID }}

jobs:
  publish:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Publish    
        run: |
          sed -i 's/run_id/'$VERSION'/g' package.json
          npm publish --ignore-scripts
